apiVersion: v1
kind: ConfigMap
metadata:
  name: es-connector-2
  labels:
    {{- include "ontotext-reconciliation.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  es-connector-2.sparql: |-
    {{ tpl (.Files.Get "files/index-manager/connectors/es-connector-2.sparql" | nindent 4) . }}
