# Can be used as alternative approach for setting up a license for GraphDB.

{{- if .Values.graphdb.enabled }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: graphdb-license
  labels:
    {{- include "ontotext-reconciliation.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  graphdb.license: {{ .Files.Get "files/graphdb/graphdb.license" | b64enc . }}

{{- end }}
