# This alternative compose provides an example on how to setup the Elasticsearch Cluster and additional services.
# The environment that will be installed will contain, Elasticsearch with two nodes, Kibana, monitoring using
# Grafana and Prometheus.
#
# Note that there are additional configurations for Prometheus and Grafana Dashboards.

#
# WARN: Mind the configurations and file paths when copying the content of the current file.
#

version: '3'

services:

#######################
#    Reconciliator    #
#######################

  reconciliator:
    container_name: reconciliator
    image: docker-registry.ontotext.com/ontotext/reconciliation/reconciliator:${RECONCILIATOR_VERSION:-1.0.0}
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      JAVA_OPTS: >-
        -Xms${RECONCILIATOR_HEAP_SIZE:-1g} -Xmx${RECONCILIATOR_HEAP_SIZE:-1g}
        -Delastic.config.file=/opt/reconciliation-config.json
        -Dspring.config.location=/opt/application.yaml
    volumes:
      - "../resources/reconciliator/reconciliation-config.json:/opt/reconciliation-config.json"
      - "../resources/reconciliator/application.yaml:/opt/application.yaml"
      - "../resources/reconciliator/preview:/opt/resources"
    ports:
      - 8080:8080
    depends_on:
      - elastic

##########################
#    Index Management    #
##########################

  index-manager:
    container_name: index-manager
    image: docker-registry.ontotext.com/ontotext/reconciliation/index-manager:${INDEX_MANAGER_VERSION:-1.0.0}
    restart: "no"
    stop_grace_period: 2m
    environment:
      JAVA_OPTS: >-
        -Xms${INDEX_MANAGER_HEAP_SIZE:-1g} -Xmx${INDEX_MANAGER_HEAP_SIZE:-1g}
        -Dspring.config.location=/opt/index-manager/application.yaml
    volumes:
      - "index_data:/opt/index-manager/"
      - "../resources/index-manager/application.yaml:/opt/index-manager/application.yaml"
      - "../resources/index-manager/connectors:/opt/index-manager/connectors"

#################
#    GraphDB    #
#################

  graphdb:
    container_name: graphdb
    image: ontotext/graphdb:${GRAPHDB_VERSION:-10.7.3}
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      GDB_JAVA_OPTS: >-
        -Xms${GRAPHDB_HEAP_SIZE:-4g} -Xmx${GRAPHDB_HEAP_SIZE:-4g}
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dhealth.max.query.time.seconds=600
        -Dgraphdb.append.request.id.headers=true
        -Dgraphdb.workbench.cors.enable=false
        -Dgraphdb.engine.entity.validate=false
# To expose the instance in domain, use the exteranl url configuration as shown below
#       -Dgraphdb.external-url=https://my.domain.com/graphdb
# You may need to enable the below configurations as well, when the GraphDB instance is behind proxy
#       -Dgraphdb.external-url.enforce.transactions=true
    volumes:
      - "graphdb_data:/opt/graphdb/home"
      - "../resources/graphdb/graphdb.license:/opt/graphdb/home/conf/graphdb.license:ro"
      - "../resources/graphdb/example-repo-config.ttl:/opt/graphdb/home/data/repositories/example/config.ttl"
      - "index_data:/opt/index-manager/"
    ports:
      - 7200:7200
      - 7300:7300

#######################
#    Elasticsearch    #
#######################

  elastic:
    container_name: elastic
    image: elasticsearch:${ELASTIC_VERSION:-7.17.18}
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ELASTIC_HEAP_SIZE:-2g} -Xmx${ELASTIC_HEAP_SIZE:-2g}"
      - cluster.initial_master_nodes=elastic,elastic02
      - node.name=elastic
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic02
    volumes:
      - "elastic_data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
      - 9500:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  elastic02:
    container_name: elastic02
    image: elasticsearch:${ELASTIC_VERSION:-7.17.18}
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ELASTIC_HEAP_SIZE:-2g} -Xmx${ELASTIC_HEAP_SIZE:-2g}"
      - cluster.initial_master_nodes=elastic,elastic02
      - node.name=elastic02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "elastic_data:/usr/share/elasticsearch/data"

################
#    Kibana    #
################

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION:-7.17.18}
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - 9401:5601

####################
#    Prometheus    #
####################

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.28.0}
    restart: unless-stopped
    ports:
      - 9091:9090
    command:
      - "--storage.tsdb.retention.time=5y"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus:/prometheus"

#################
#    Grafana    #
#################

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-8.0.3}
    restart: unless-stopped
    ports:
      - 9092:3000
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana/provisioning/:/etc/grafana/provisioning/"

#################
#    Volumes    #
#################

volumes:
  index_data:
    external: true
  graphdb_data:
  elastic_data:
  prometheus:
  grafana_data:
