{
 "title": "Reconciliator",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of queries per day",
   "type": "timeseries",
   "description": "Total number of Reconciliator service queries per day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(recon_query_seconds_count[1d])",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Number of queries per hour",
   "type": "timeseries",
   "description": "Total number of Reconciliator service queries per hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(recon_query_seconds_count[1h])",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Number of queries per minute",
   "type": "timeseries",
   "description": "Total number of Reconciliator service queries per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(recon_query_seconds_count[1m])",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Average query time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(recon_query_seconds_sum[1m]) / increase(recon_query_seconds_count[1m]) * 1000",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  { "title": "Elastic Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Elastic Batch Query - Average query time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "increase(elastic_query_batch_seconds_sum[1m]) / increase(elastic_query_batch_seconds_count[1m]) * 1000",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Elastic Non-Batch Query - Average query time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "increase(elastic_query_seconds_sum[1m]) / increase(elastic_query_seconds_count[1m]) * 1000",
     "legendFormat": "{{operationName}}"
    }
   ]
  }
 ]
}