{{- if and .Values.reconciliator.enabled (eq .Values.reconciliator.provision.reconciliation.configmap "reconciliation-config")}}

{{- $sourcefile := (required "Either provide 'reconciliator.provision.reconciliation.sourcefile' or override the 'reconciliator.provision.reconciliation.configmap'!" .Values.reconciliator.provision.reconciliation.sourcefile) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: reconciliation-config
  labels:
    {{- include "ontotext-reconciliation.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  reconciliation-config.json: |-
    {{ tpl (.Files.Get $sourcefile | nindent 4) . }}

{{- end }}
